---
title: "MasterClass: Predictive Analytics in Insurance Claims Data"
output:
  html_notebook: default
  html_document: default
---
By *Rendani Mbuvha*

#*Predictive Analytics in Insurance Claims Data*
This notebook will provide all the interactive material for the MasterClass: Predictive Analytics in Insurance Claims Data workshop. The workshop will cover:

+ Traditional statistical analysis of claims data 
+ Machine Learning Techiques

    + Unsupervised learning techiques for claims data analysis 
    + Supervised learning techiques for claims data analysis

The workshop will be based on data from the Computational Actuarial Science Package 
##**Preliminaries - To be done before the workshop**

**Workshop attendees are requested to bring their own laptops with the programmes and packages below installed.**

First of all, we need to install R, R studio, and the required packages. 

* Download and install R according to  the instructions [here](https://cran.rstudio.com/)  
* Download and install R studio according to instructions [here](https://www.rstudio.com/products/rstudio/download/#download) (*Optional*)

In R, install the following libraries:

  +   ROCR
  +   glmnet
  +   insuranceData
  +   ggplot2
  +   CASdatasets
  
  > Use the command on the R console *install.packages("package-name")*
  
##**Recommended Intoductory R Material**

While the workshop will briefly touch on some basics of R. R will mainly be used as an analysis tool. Some good introductory R material can found here:

  + [Radford Neal's R Course](http://www.cs.utoronto.ca/~radford/csc121.S17/) (Browsing through weeks 1-4 is sufficient)
  
  + [Introduction to some aspects of R (Chi Yau)](http://www.r-tutor.com/r-introduction)
  

Full workshop materials will be uploaded on **24 August 2018**.  
